function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t228__list_item a[href='"+url+"']").addClass("t-active");$(".t228__list_item a[href='"+url+"/']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t228__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t228__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function t228_checkAnchorLinks(recid){if($(window).width()>=960){var t228_navLinks=$("#rec"+recid+" .t228__list_item a:not(.tooltipstered)[href*='#']");if(t228_navLinks.length>0){setTimeout(function(){t228_catchScroll(t228_navLinks)},500)}}}
function t228_catchScroll(t228_navLinks){var t228_clickedSectionId=null,t228_sections=new Array(),t228_sectionIdTonavigationLink=[],t228_interval=100,t228_lastCall,t228_timeoutId;t228_navLinks=$(t228_navLinks.get().reverse());t228_navLinks.each(function(){var t228_cursection=t228_getSectionByHref($(this));if(typeof t228_cursection.attr("id")!="undefined"){t228_sections.push(t228_cursection)}
t228_sectionIdTonavigationLink[t228_cursection.attr("id")]=$(this)});t228_updateSectionsOffsets(t228_sections);t228_sections.sort(function(a,b){return b.attr("data-offset-top")-a.attr("data-offset-top")});$(window).bind('resize',t_throttle(function(){t228_updateSectionsOffsets(t228_sections)},200));$('.t228').bind('displayChanged',function(){t228_updateSectionsOffsets(t228_sections)});setInterval(function(){t228_updateSectionsOffsets(t228_sections)},5000);t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId);t228_navLinks.click(function(){var t228_clickedSection=t228_getSectionByHref($(this));if(!$(this).hasClass("tooltipstered")&&typeof t228_clickedSection.attr("id")!="undefined"){t228_navLinks.removeClass('t-active');$(this).addClass('t-active');t228_clickedSectionId=t228_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t228_now=new Date().getTime();if(t228_lastCall&&t228_now<(t228_lastCall+t228_interval)){clearTimeout(t228_timeoutId);t228_timeoutId=setTimeout(function(){t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)},t228_interval-(t228_now-t228_lastCall))}else{t228_lastCall=t228_now;t228_clickedSectionId=t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId)}})}
function t228_updateSectionsOffsets(sections){$(sections).each(function(){var t228_curSection=$(this);t228_curSection.attr("data-offset-top",t228_curSection.offset().top)})}
function t228_getSectionByHref(curlink){var t228_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(t228_curLinkValue[0]=='/'){t228_curLinkValue=t228_curLinkValue.substring(1)}
if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t228_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t228_curLinkValue.substring(1)+"']")}}
function t228_highlightNavLinks(t228_navLinks,t228_sections,t228_sectionIdTonavigationLink,t228_clickedSectionId){var t228_scrollPosition=$(window).scrollTop(),t228_valueToReturn=t228_clickedSectionId;if(t228_sections.length!=0&&t228_clickedSectionId==null&&t228_sections[t228_sections.length-1].attr("data-offset-top")>(t228_scrollPosition+300)){t228_navLinks.removeClass('t-active');return null}
$(t228_sections).each(function(e){var t228_curSection=$(this),t228_sectionTop=t228_curSection.attr("data-offset-top"),t228_id=t228_curSection.attr('id'),t228_navLink=t228_sectionIdTonavigationLink[t228_id];if(((t228_scrollPosition+300)>=t228_sectionTop)||(t228_sections[0].attr("id")==t228_id&&t228_scrollPosition>=$(document).height()-$(window).height())){if(t228_clickedSectionId==null&&!t228_navLink.hasClass('t-active')){t228_navLinks.removeClass('t-active');t228_navLink.addClass('t-active');t228_valueToReturn=null}else{if(t228_clickedSectionId!=null&&t228_id==t228_clickedSectionId){t228_valueToReturn=null}}
return!1}});return t228_valueToReturn}
function t228_setPath(){}
function t228_setWidth(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var left_exist=el.find('.t228__leftcontainer').length;var left_w=el.find('.t228__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.t228__rightcontainer').length;var right_w=el.find('.t228__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.t228__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".t228__maincontainer").outerWidth();if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".t228__leftside").css("min-width",max_w+"px");el.find(".t228__rightside").css("min-width",max_w+"px");el.find(".t228__list").removeClass("t228__list_hidden")}}else{el.find(".t228__leftside").css("min-width","");el.find(".t228__rightside").css("min-width","")}})}}
function t228_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t228_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");var topoffset=el.data('top-offset');if(topoffset&&parseInt(topoffset)>0){el.animate({"opacity":"1","top":topoffset+"px"},200,function(){})}else{el.animate({"opacity":"1","top":"0px"},200,function(){})}}}else{el.stop();el.css("visibility","hidden");el.css("opacity","0")}}})}}
function t228_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t228").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t228_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t228"),burger=el.find(".t228__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t228_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}
function t270_scroll(hash,offset){var $root=$('html, body');var target="";try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message)}
if(target.length==0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length==0){return!1}}
$root.animate({scrollTop:target.offset().top-offset},500,function(){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}});return!0}
function t395_init(recid){var el=$('#rec'+recid);el.find('.t395__tab').click(function(){el.find('.t395__tab').removeClass('t395__tab_active');$(this).addClass('t395__tab_active');t395_alltabs_updateContent(recid);t395_updateSelect(recid);$('.t347').trigger('displayChanged');$('.t346').trigger('displayChanged');$('.t764, .t506, .t675, .t570, .t774, .t397, .t504, .t498, .t778, .t592, .t477, .t480, .t511, .t552, .t132, .t598, .t599, .t650, .t659, .t351, .t353, .t341, .t404, .t385, .t386, .t409, .t384, .t279, .t349, .t433, .t418, .t268, .t428, .t532, .t601, .t478, .t228, .t229, .t456, .t520, .t615, .t517, .t688, .t744, .t609, .t604, .t670, .t686, .t554, .t230, .t486, .t117, .t422, .t616, .t121, .t801, .t412, .t760, .t827, .t829, .t762, .t826, .t734, .t726, .t799, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t518, .t396, .t728, .t738, .t544, .t780, .t698, .t509, .t431, .t700, .t223, .t539, .t577, .t226, .t754, .t776, .t-feed, .t-store, .t923').trigger('displayChanged');setTimeout(function(){$('.t351, .t353, .t341, .t404, .t385, .t386, .t409, .t384, .t279, .t349, .t410, .t433, .t418, .t520, .t829, .t396, .t738').trigger('displayChanged')},50);t395_startUpdateLazyLoad($(this));if(window.lazy=='y'){t_lazyload_update()}});t395_alltabs_updateContent(recid);t395_updateContentBySelect(recid);var bgcolor=el.css("background-color");var bgcolor_target=el.find(".t395__select, .t395__firefoxfix");bgcolor_target.css("background",bgcolor);$('#rec'+recid+' .t395__wrapper_mobile .t395__select option').first().attr('selected',!0)}
function t395_alltabs_updateContent(recid){var el=$('#rec'+recid);el.find(".t395__tab").each(function(i){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.attr('data-connect-with-tab','yes');rec_el.attr('data-animationappear','off');rec_el.addClass('t379__off')})});el.find(".t395__tab_active").each(function(i){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.removeClass('t379__off');rec_el.css('opacity','')})})}
function t395_updateContentBySelect(recid){var el=$('#rec'+recid);el.find(".t395__select").change(function(){var select_val=el.find(".t395__select").val();var tab_index=el.find(".t395__tab[data-tab-rec-ids='"+select_val+"']");tab_index.trigger('click')})}
function t395_updateSelect(recid){var el=$('#rec'+recid);var current_tab=el.find(".t395__tab_active").attr('data-tab-rec-ids');var el_select=el.find(".t395__select");el_select.val(current_tab)}
function t395_startUpdateLazyLoad($this){var rec_ids=$this.attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);var video=rec_el.find('.t-video-lazyload');if(video.length>0){t395_updateVideoLazyLoad(video)}})}
function t395_updateVideoLazyLoad(video){setTimeout(function(){video.each(function(){var div=$(this);if(!div.hasClass('t-video__isload')){var height=div.attr('data-videolazy-height')?$(this).attr('data-videolazy-height'):'100%';if(height.indexOf('vh')!=-1){height='100%'}
var videoId=div.attr('data-videolazy-id').trim();var blockId=div.attr('data-blocklazy-id')||'';if(typeof div.attr('data-videolazy-two-id')!='undefined'){var videoTwoId='_'+div.attr('data-videolazy-two-id')+'_'}else{var videoTwoId=''}
if(div.attr('data-videolazy-type')=='youtube'){div.find('iframe').remove();div.prepend('<iframe id="youtubeiframe'+videoTwoId+blockId+'" width="100%" height="'+height+'" src="//www.youtube.com/embed/'+videoId+'?rel=0&fmt=18&html5=1&showinfo=0" frameborder="0" allowfullscreen></iframe>')}}
div.addClass('t-video__isload')})},0)}
function t539_equalHeight(recid,blocks){if(blocks==''||parseInt(blocks)==0){return!1}
var t539__el=$('#rec'+recid),t539__cols=t539__el.find(".t539__textwrapper");t539__cols.css("height","auto");if($(window).width()<=480){t539__el.find('.t539').css('visibility','visible');return}
if($(window).width()<=960){var t539__perRow=2}
else{var t539__perRow=+blocks}
for(var i=0;i<t539__cols.length;i+=t539__perRow)
{var t539__maxHeight=0,t539__row=t539__cols.slice(i,i+t539__perRow);t539__row.each(function(){var t539__itemHeight=$(this).outerHeight();if(t539__itemHeight>t539__maxHeight){t539__maxHeight=t539__itemHeight}});t539__row.css("height",t539__maxHeight)}
t539__el.find('.t539').css('visibility','visible')};function t539_setHeight(recid){var t539__el=$("#rec"+recid),t539__image=t539__el.find(".t539__bgimg:first"),t539__width=t539__image.attr("data-image-width"),t539__height=t539__image.attr("data-image-height"),t539__ratio=t539__height/t539__width,t539__padding=t539__ratio*100;$("#rec"+recid+" .t539__bgimg").css("padding-bottom",t539__padding+"%")}
function t577_equalHeight(recid){var el=$('#rec'+recid);el.find('.t577').css('visibility','visible');el.find('.t577__textwrapper').css('height','auto');el.find('.t577__descr').css('height','auto');$('#rec'+recid+' .t577__row').each(function(){var highestBox=0;$('.t577__descr',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t577__descr',this).css('height',highestBox)}else{$('.t577__descr',this).css('height',"auto")}});$('#rec'+recid+' .t577__row').each(function(){var highestBox=0;$('.t577__textwrapper',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960&&$(this).is(':visible')){$('.t577__textwrapper',this).css('height',highestBox)}else{$('.t577__textwrapper',this).css('height',"auto")}})};function t602_init(recid){var t602_lastCall,t602_timeoutId,t602_interval=100;$(window).scroll(function(){var t602_now=new Date().getTime();if(t602_lastCall&&t602_now<(t602_lastCall+t602_interval)){clearTimeout(t602_timeoutId);t602_timeoutId=setTimeout(function(){t602_lastCall=t602_now;t602_setProgressBarWidth(recid)},t602_interval-(t602_now-t602_lastCall))}else{t602_lastCall=t602_now;t602_setProgressBarWidth(recid)}})}
function t602_setProgressBarWidth(recid){var t602_windowScrollTop=$(window).scrollTop(),t602_docHeight=$(document).height(),t602_winHeight=$(window).height();t602_scrollPercent=(t602_windowScrollTop/(t602_docHeight-t602_winHeight))*100;$(".t602__indicator").css('width',t602_scrollPercent+'%')}
function t608_setHeight(recid){var el=$("#rec"+recid);var image=el.find(".t608__bgimg");image.each(function(){var width=$(this).attr("data-image-width");var height=$(this).attr("data-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t635_init(recid){t635_startType(recid)}
function t635_startType(recid){var t635_el=$('#rec'+recid),t635_data=t635_el.find(".t635__textholder"),t635_animRecId=t635_data.attr("data-recid"),t635_animText=t635_findAnimElem(t635_animRecId),t635_phrasesList=[],t635_phrase1=t635_data.attr("data-text1"),t635_phrase2=t635_data.attr("data-text2"),t635_phrase3=t635_data.attr("data-text3"),t635_phrase4=t635_data.attr("data-text4"),t635_phrase5=t635_data.attr("data-text5"),t635_speed=t635_data.attr("data-speed"),t635_loop=t635_data.attr("data-loop"),t635_backspaceDelay=t635_data.attr("data-backspacing-delay");if(typeof t635_animText=="undefined"){return}
if(typeof t635_phrase1!="undefined"){t635_phrasesList.push(t635_phrase1.slice(0,80))}
if(typeof t635_phrase2!="undefined"){t635_phrasesList.push(t635_phrase2.slice(0,80))}
if(typeof t635_phrase3!="undefined"){t635_phrasesList.push(t635_phrase3.slice(0,80))}
if(typeof t635_phrase4!="undefined"){t635_phrasesList.push(t635_phrase4.slice(0,80))}
if(typeof t635_phrase5!="undefined"){t635_phrasesList.push(t635_phrase5.slice(0,80))}
if(t635_animText.length!=0&&t635_phrasesList.length!=0){var t635_animTextHtml=t635_animText.html(),t635_animTextSplitted=t635_animTextHtml.split("|"),t635_curWin=$(window);t635_animText.html(t635_animTextSplitted[0]+"<span class=\"t635__typing-text\"></span>"+t635_animTextSplitted[1]);t635_updateAnimTextLimits(t635_animRecId);t635_curWin.bind('resize',t_throttle(function(){t635_updateAnimTextLimits(t635_animRecId)},200));setInterval(function(){t635_updateAnimTextLimits(t635_animRecId)},5000);var t635_animatedText=$("#rec"+t635_animRecId+" .t635__typing-text"),t635_animTextTop=t635_animatedText.attr("data-top-limit"),t635_animTextBottom=t635_animatedText.attr("data-bottom-limit"),t635_winTop=t635_curWin.scrollTop(),t635_winBottom=t635_winTop+t635_curWin.height();t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay);if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}
t635_curWin.bind('scroll',t_throttle(function(){t635_animTextTop=t635_animatedText.attr("data-top-limit");t635_animTextBottom=t635_animatedText.attr("data-bottom-limit");t635_winTop=t635_curWin.scrollTop();t635_winBottom=t635_winTop+t635_curWin.height();if(t635_animTextBottom<t635_winTop||t635_animTextTop>t635_winBottom){$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').pauseTyping();$("#rec"+t635_animRecId+" .t635__typing-text").html("")}else{$("#rec"+t635_animRecId+" .t635__typing-text").data('typed').continueTyping()}},200))}}
function t635_findAnimElem(animRecId){var animRec=$("#rec"+animRecId);var animH1=animRec.find("h1:contains(\'|\')").last();var animH2=animRec.find("h2:contains(\'|\')").last();var animH3=animRec.find("h3:contains(\'|\')").last();var animDiv=animRec.find("div:contains(\'|\')").last();if(typeof animH1!="undefined"&&animH1.length>0){return animH1}
if(typeof animH2!="undefined"&&animH2.length>0){return animH2}
if(typeof animH3!="undefined"&&animH3.length>0){return animH3}
if(typeof animDiv!="undefined"&&animDiv.length>0){return animDiv}}
function t635_updateAnimTextLimits(t635_animRecId){var t635_animatedBlock=$("#rec"+t635_animRecId),t635_animatedText=t635_animatedBlock.find(".t635__typing-text");t635_animatedText.attr("data-top-limit",t635_animatedText.offset().top);t635_animatedText.attr("data-bottom-limit",(t635_animatedBlock.offset().top+t635_animatedBlock.height()))}
function t635_animateText(t635_animRecId,t635_phrasesList,t635_speed,t635_loop,t635_backspaceDelay){if(typeof t635_speed=="undefined"){t635_speed=40}
if(typeof t635_backspaceDelay=="undefined"){t635_backspaceDelay=800}
if(typeof t635_loop=="undefined"){t635_loop=!0}else{t635_loop=!1}
$("#rec"+t635_animRecId+" .t635__typing-text").typed({strings:t635_phrasesList,typeSpeed:t635_speed*1,startDelay:600,backSpeed:10,backDelay:t635_backspaceDelay*1,loop:t635_loop,contentType:'text'})}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$("#rec"+recid),play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$("#rec"+recid),body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t670__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t686_init(recid){setTimeout(function(){t686_setHeight(recid)},500);var t686__doResize;$(window).resize(function(){clearTimeout(t686__doResize);t686__doResize=setTimeout(function(){t686_setHeight(recid)},200)})}
function t686_setHeight(recid){var t686_el=$('#rec'+recid+' .t686'),t686_ratio=t686_el.attr('data-tile-ratio'),t686_ratioHeight=t686_el.find('.t686__col').width()*t686_ratio;t686_el.find('.t686__row').each(function(){var t686_largestHeight=0,t686_currow=$(this);$('.t686__table',this).each(function(){var t686_curCol=$(this),t686_curColHeight=t686_curCol.find(".t686__textwrapper").outerHeight();if($(this).find(".t686__cell").hasClass("t686__button-bottom")){t686_curColHeight+=t686_curCol.find(".t686__button-container").outerHeight()}
if(t686_curColHeight>t686_largestHeight){t686_largestHeight=t686_curColHeight}});if($(window).width()>=960){if(t686_largestHeight>t686_ratioHeight){$('.t686__table',this).css('height',t686_largestHeight)}
else{$('.t686__table',this).css('height',t686_ratioHeight)}
$('.t686__table',this).css('min-height','auto')}else{$('.t686__table',this).css('min-height',t686_ratioHeight);$('.t686__table',this).css('height','')}
if(t686_GetIEVersion()>0){var curRowHeight=$('.t686__table',this).css('height');$('.t686__bg',this).css('height',curRowHeight);$('.t686__overlay',this).css('height',curRowHeight)}})}
function t686_GetIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0){return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)))}else{if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}}
function t690_onSuccess(t690_form){var t690_inputsWrapper=t690_form.find('.t-form__inputsbox');var t690_inputsHeight=t690_inputsWrapper.height();var t690_inputsOffset=t690_inputsWrapper.offset().top;var t690_inputsBottom=t690_inputsHeight+t690_inputsOffset;var t690_targetOffset=t690_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t690_target=t690_targetOffset-200}else{var t690_target=t690_targetOffset-100}
if(t690_targetOffset>$(window).scrollTop()||($(document).height()-t690_inputsBottom)<($(window).height()-100)){t690_inputsWrapper.addClass('t690__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t690_target},400);setTimeout(function(){t690_inputsWrapper.addClass('t690__inputsbox_hidden')},400)}
var successurl=t690_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_onSuccess(t702_form){var t702_inputsWrapper=t702_form.find('.t-form__inputsbox');var t702_inputsHeight=t702_inputsWrapper.height();var t702_inputsOffset=t702_inputsWrapper.offset().top;var t702_inputsBottom=t702_inputsHeight+t702_inputsOffset;var t702_targetOffset=t702_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t702_target=t702_targetOffset-200}else{var t702_target=t702_targetOffset-100}
if(t702_targetOffset>$(window).scrollTop()||($(document).height()-t702_inputsBottom)<($(window).height()-100)){t702_inputsWrapper.addClass('t702__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t702_target},400);setTimeout(function(){t702_inputsWrapper.addClass('t702__inputsbox_hidden')},400)}
var successurl=t702_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t702_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t702_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t702_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t-popup');popup.css('display','block');el.find('.t-range').trigger('popupOpened');if(window.lazy=='y'){t_lazyload_update()}
setTimeout(function(){popup.find('.t-popup__container').addClass('t-popup__container-animated');popup.addClass('t-popup_show')},50);$('body').addClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t702_lockScroll()},500)}
el.find('.t-popup').mousedown(function(e){var windowWidth=$(window).width();var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(e.clientX>windowWithoutScrollBar){return}
if(e.target==this){t702_closePopup()}});el.find('.t-popup__close').click(function(e){t702_closePopup()});el.find('a[href*="#"]').click(function(e){var url=$(this).attr('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){$('body').addClass('t-body_popupshowed')},300)}}});$(document).keydown(function(e){if(e.keyCode==27){t702_closePopup()}})}
function t702_closePopup(){$('body').removeClass('t-body_popupshowed t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t702_unlockScroll()}
$('.t-popup').removeClass('t-popup_show');setTimeout(function(){$('.t-popup').not('.t-popup_show').css('display','none')},300)}
function t702_resizePopup(recid){var el=$("#rec"+recid),div=el.find(".t-popup__container").height(),win=$(window).height()-120,popup=el.find(".t-popup__container");if(div>win){popup.addClass('t-popup__container-static')}else{popup.removeClass('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t-popup'),hook=el.attr('data-tooltip-hook'),analitics=el.attr('data-track-popup');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t702_showPopup(recid);t702_resizePopup(recid);e.preventDefault();if(window.lazy=='y'){t_lazyload_update()}
if(analitics>''){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}})}}
function t722_onSuccess(t722_form){var t722_inputsWrapper=t722_form.find('.t-form__inputsbox');var t722_inputsHeight=t722_inputsWrapper.height();var t722_inputsOffset=t722_inputsWrapper.offset().top;var t722_inputsBottom=t722_inputsHeight+t722_inputsOffset;var t722_targetOffset=t722_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t722_target=t722_targetOffset-200}else{var t722_target=t722_targetOffset-100}
if(t722_targetOffset>$(window).scrollTop()||($(document).height()-t722_inputsBottom)<($(window).height()-100)){t722_inputsWrapper.addClass('t722__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t722_target},400);setTimeout(function(){t722_inputsWrapper.addClass('t722__inputsbox_hidden')},400)}
var successurl=t722_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t722_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t764_updateSlider(recid){var el=$('#rec'+recid);t_slds_SliderWidth(recid);sliderWrapper=el.find('.t-slds__items-wrapper');sliderWidth=el.find('.t-slds__container').width();pos=parseFloat(sliderWrapper.attr('data-slider-pos'));sliderWrapper.css({transform:'translate3d(-'+(sliderWidth*pos)+'px, 0, 0)'});t_slds_UpdateSliderHeight(recid);t_slds_UpdateSliderArrowsHeight(recid)}
function t794_init(recid){var hook=$("#rec"+recid+" .t794").attr("data-tooltip-hook");if(typeof hook=="undefined"||hook==""){return};var hookLinks=$("a[href='"+hook+"']");hookLinks.addClass("t794__tm-link");hookLinks.attr("data-tooltip-menu-id",recid);t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t794_highlight()}
function t794_setUpMenu(recid,hookLinks){var submenu=$("#rec"+recid+" .t794__tooltip-menu");if(isMobile){t794_setUpMenu_mobile(recid,hookLinks,submenu)}else{t794_setUpMenu_desktop(recid,hookLinks,submenu)}
$(window).bind('scroll',t_throttle(function(){if(submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}},300));$(".t794__tooltip-menu a[href*=#]").click(function(){t794_hideSubmenu(submenu);$('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466').trigger('clickedAnchorInTooltipMenu');$(".t794__tooltip-menu a[href*=#]").removeClass('t-active');$(this).addClass('t-active')})}
function t794_setUpMenu_mobile(recid,hookLinks,submenu){var vIndent=$("#rec"+recid+" .t794").attr('data-tooltip-margin');hookLinks.on("click",function(e){if(submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}else{var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)}
e.preventDefault()});$(document).click(function(e){var isInsideSubmenu=($(e.target).hasClass("t794__tooltip-menu")||$(e.target).parents(".t794__tooltip-menu").length>0);var isAnchor=($(e.target).hasClass("t794__tm-link")||$(e.target).parents(".t794__tm-link").length>0);if(isAnchor){var curAnchor;if($(e.target).hasClass("t794__tm-link")){curAnchor=$(e.target)}else{curAnchor=$(e.target).parents(".t794__tm-link")}
if(curAnchor.attr("data-tooltip-menu-id")!=recid&&submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}}
if(!isInsideSubmenu&&!isAnchor&&submenu.hasClass("t794__tooltip-menu_show")){t794_hideSubmenu(submenu)}})}
function t794_setUpMenu_desktop(recid,hookLinks,submenu){var vIndent=$("#rec"+recid+" .t794").attr('data-tooltip-margin');var timer;hookLinks.add(submenu).on("mouseover",function(){if($(this).hasClass("t794__tooltip-menu")&&!$(this).hasClass("t794__tooltip-menu_show")){return}
clearTimeout(timer);if($(this).hasClass("t794__tooltip-menu")&&submenu.hasClass("t794__tooltip-menu_show")){return}
var curAnchor=$(this);t794_showSubmenu(curAnchor,submenu,vIndent)});hookLinks.add(submenu).on("mouseout",function(){timer=setTimeout(function(){t794_hideSubmenu(submenu)},300)});hookLinks.on("click",function(e){e.preventDefault()})}
function t794_showSubmenu(curAnchor,submenu,vIndent){var submenuHeight=submenu.outerHeight();var submenuWidth=submenu.outerWidth();var anchorHeight=curAnchor.height();var anchorWidth=curAnchor.width();if(curAnchor.hasClass('t-btn')){anchorWidth=curAnchor.outerWidth()}
var winHeight=$(window).height();var winWidth=$(window).width();var scrollTop=$(window).scrollTop();var anchorLeft=curAnchor.offset().left;if(typeof vIndent!="undefined"&&vIndent!=""){vIndent=vIndent.replace("px","")*1;vIndent=vIndent+10}
var posy=curAnchor.offset().top+anchorHeight+vIndent;var posx=anchorLeft;if(posy+submenuHeight>scrollTop+winHeight){posy=Math.max(posy-submenuHeight-anchorHeight-vIndent*2,scrollTop);submenu.removeClass("t794__tooltip-menu_bottom").addClass("t794__tooltip-menu_top")}else{submenu.removeClass("t794__tooltip-menu_top").addClass("t794__tooltip-menu_bottom")}
if(posx+submenuWidth/2<winWidth){posx=posx+(anchorWidth-submenuWidth)/2;if(posx<0){posx=10}}else{posx=winWidth-submenuWidth-10}
submenu.css({"display":"block","left":posx,"top":posy});submenu[0].offsetHeight;submenu.addClass("t794__tooltip-menu_show");curAnchor.addClass("t794__tm-link_active")}
function t794_hideSubmenu(submenu){submenu.css({"display":"","left":"","top":""});submenu.removeClass("t794__tooltip-menu_show");$(".t794__tm-link_active").removeClass("t794__tm-link_active")}
function t794_addArrow(recid,hookLinks){var arrow=$("#rec"+recid+" .t794").attr('data-add-arrow');if(typeof arrow=="undefined"||arrow==""){return};hookLinks.each(function(){var arrowHeight=$(this).height();$(this).append("<div class=\"t794__arrow\" style=\"height: "+arrowHeight+"px;\"></div>")})}
function t794_highlight(){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t794__list_item a[href='"+url+"']").addClass("t-active");$(".t794__list_item a[href='"+url+"/']").addClass("t-active");$(".t794__list_item a[href='"+pathname+"']").addClass("t-active");$(".t794__list_item a[href='/"+pathname+"']").addClass("t-active");$(".t794__list_item a[href='"+pathname+"/']").addClass("t-active");$(".t794__list_item a[href='/"+pathname+"/']").addClass("t-active");if(hash){$(".t794__list_item a[href='"+hash+"']").addClass("t-active")}}
function t796_init(recid){var el=$("#rec"+recid);var shapeEl=el.find(".t796__shape-border");var recs=el.find(".t796").attr("data-shape-rec-ids");if(typeof recs!="undefined"){recs=recs.split(",");recs.forEach(function(rec_id,i,arr){var curRec=$("#rec"+rec_id);var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)})}else{var excludes="[data-record-type='215'],[data-record-type='706'],[data-record-type='651'],[data-record-type='825'],[data-record-type='708']";if(shapeEl.hasClass('t796__shape-border_top')||shapeEl.hasClass('t796__shape-border_top-flip')){var curRec=el.next(".r");if(curRec.is(excludes)){curRec=curRec.next(".r")}}
if(shapeEl.hasClass('t796__shape-border_bottom')||shapeEl.hasClass('t796__shape-border_bottom-flip')){var curRec=el.prev(".r");if(curRec.is(excludes)){curRec=curRec.prev(".r")}}
if(curRec.length!=0){var curShapeEl=shapeEl.clone();t796_setColor(el,curShapeEl);t796_addDivider(curRec,curShapeEl)}}}
function t796_addDivider(curRec,curShapeEl){curRec.attr("data-animationappear","off").removeClass('r_hidden');var coverWrapper=curRec.find(".t-cover");var zeroWrapper=curRec.find(".t396");if(coverWrapper.length>0||zeroWrapper.length>0){if(coverWrapper.length>0){coverWrapper.find(".t-cover__filter").after(curShapeEl)}
if(zeroWrapper.length>0){zeroWrapper.after(curShapeEl);curRec.css("position","relative")}
curShapeEl.css("display","block")}else{var wrapper=curRec;var curRecType=curRec.attr("data-record-type");if(wrapper.length==0){return!0}
wrapper.append(curShapeEl);wrapper.css("position","relative");if(curRecType!="554"&&curRecType!="125"){wrapper.children("div").first().css({"position":"relative","z-index":"1"}).addClass("t796_cont-near-shape-divider")}
if(curRecType=="734"||curRecType=="675"||curRecType=="279"||curRecType=="694"||curRecType=="195"){curShapeEl.css("z-index","1")}
curShapeEl.css("display","block")}}
function t796_setColor(el,curShapeEl){if(typeof curShapeEl.attr("data-fill-color")!="undefined"){return}
if(curShapeEl.hasClass("t796__shape-border_bottom")||curShapeEl.hasClass("t796__shape-border_bottom-flip")){var nearestBlock=el.next(".r")}else{var nearestBlock=el.prev(".r")}
if(nearestBlock.length==0){return}
var fillColor=nearestBlock.attr("data-bg-color");if(typeof fillColor=="undefined"){return}
curShapeEl.find(".t796__svg").css("fill",fillColor)}
function t819_init(recid){var rec=$('#rec'+recid);var curMode=$('.t-records').attr('data-tilda-mode');var tab=rec.find('.t819__tab');var select=rec.find('.t819__select');var content=rec.find('.t819__content');if(curMode!='edit'&&curMode!='preview'){t819_scrollToTabs(recid)}
t819_showTabByUrl(recid,tab,content,select);t819_showTab(tab,content,recid);t819_showTabMobile(select,content,recid)}
function t819_showTab(tab,content,recid){var tabNumber;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');tab.on('click',function(e){tabNumber=$(this).attr('data-tab-number');tab.removeClass('t819__tab_active');content.removeClass('t819__content_active');$(this).addClass('t819__tab_active');t819_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumber){$(content[i]).addClass('t819__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy=='y'){t_lazyload_update()}}
e.preventDefault()})}
function t819_showTabMobile(select,content,recid){var tabNumberMobile;var curUrl=window.location.href;var curMode=$('.t-records').attr('data-tilda-mode');select.change(function(e){tabNumberMobile=$(this).val();content.removeClass('t819__content_active');t819_removeUrl();content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabNumberMobile){$(content[i]).addClass('t819__content_active')}});if(curMode!='edit'&&curMode!='preview'){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumberMobile)}}
if(typeof $('.t-records').attr('data-tilda-mode')=='undefined'){if(window.lazy=='y'){t_lazyload_update()}}
e.preventDefault()})}
function t819_showTabByUrl(recid,tab,content,select){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf(recid+'-');var tabIndex=curUrl.substring(tabIndexNumber+recid.length+1);if(tabIndexNumber!=-1){tab.each(function(i){if($(tab[i]).attr('data-tab-number')==tabIndex){$(tab[i]).addClass('t819__tab_active')}});content.each(function(i){if($(content[i]).attr('data-tab-content-number')==tabIndex){$(content[i]).addClass('t819__content_active')}});select.val(tabIndex)}else{tab.first().addClass('t819__tab_active');content.first().addClass('t819__content_active')}}
function t819_scrollToTabs(recid){var curUrl=window.location.href;var tabIndexNumber=curUrl.indexOf('#!/tab/');var tabIndexNumberStart=curUrl.indexOf('tab/');if(tabIndexNumber!=-1){var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length)
if(+tabRec==+recid){var tabBlock=$('#rec'+tabRec).find('.t819');var targetOffset=tabBlock.offset().top;if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
$('html, body').animate({scrollTop:target},400)}}}
function t819_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!=-1){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}}}
function t835_init(recid){var rec=$('#rec'+recid);var quiz=rec.find('.t835__quiz');var quizWrapper=rec.find('.t835__quiz-wrapper');var quizFormWrapper=rec.find('.t835__quiz-form-wrapper');var form=rec.find('.t835 .t-form');var quizQuestion=rec.find('.t835 .t-input-group');var prevBtn=rec.find('.t835__btn_prev');var nextBtn=rec.find('.t835__btn_next');var resultBtn=rec.find('.t835__btn_result');var errorBoxMiddle=rec.find('.t-form__errorbox-middle .t-form__errorbox-wrapper');var submitBtnWrapper=rec.find('.t835 .t-form__submit');var btnSubmit=rec.find('.t835 .t-submit');var captureFormHTML='<div class="t835__capture-form"></div>';rec.find('.t835 .t-form__errorbox-middle').before(captureFormHTML);var quizDescriptionHeight=rec.find('.t835__quiz-description-wrapper').outerHeight(!0);var resultTitleHeight=rec.find('.t835__result-title').outerHeight(!0);var quizQuestionNumber=0;form.removeClass('js-form-proccess');t835_workWithAnswerCode(rec);quizQuestion.each(function(i){$(quizQuestion[i]).attr('data-question-number',i)});t835_wrapCaptureForm(rec);var captureForm=rec.find('.t835__capture-form');t835_showCounter(rec,quizQuestionNumber);t835_disabledPrevBtn(rec,quizQuestionNumber);t835_checkLength(rec);prevBtn.click(function(e){if(quizQuestionNumber>0){quizQuestionNumber--}
t835_setProgress(rec,-1);if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy=='y'){t_lazyload_update()}}
t835_awayFromResultScreen(rec);t835_showCounter(rec,quizQuestionNumber);t835_hideError(rec,quizQuestionNumber);t835_disabledPrevBtn(rec,quizQuestionNumber);t835_switchQuestion(rec,quizQuestionNumber);t835_scrollToTop(quizFormWrapper);e.preventDefault()});nextBtn.click(function(e){if(quizWrapper.hasClass('t835__quiz-published')){var showErrors=t835_setError(rec,quizQuestionNumber)}
if(showErrors){errorBoxMiddle.hide()}
if(!showErrors){quizQuestionNumber++;prevBtn.attr('disabled',!1);t835_setProgress(rec,1);t835_showCounter(rec,quizQuestionNumber);t835_switchQuestion(rec,quizQuestionNumber);t835_scrollToTop(quizFormWrapper)}
if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy=='y'){t_lazyload_update()}}
e.preventDefault()});quizQuestion.keypress(function(e){if(event.keyCode===13&&!form.hasClass('js-form-proccess')){if(quizWrapper.hasClass('t835__quiz-published')){var showErrors=t835_setError(rec,quizQuestionNumber)}
var questionArr=t835_createQuestionArr(rec);if(showErrors){errorBoxMiddle.hide()}
prevBtn.attr('disabled',!1);if(!showErrors){quizQuestionNumber++;t835_setProgress(rec,1);if(quizQuestionNumber<questionArr.length){t835_switchQuestion(rec,quizQuestionNumber)}else{t835_switchResultScreen(rec);form.addClass('js-form-proccess')}
t835_scrollToTop(quizFormWrapper);t835_disabledPrevBtn(rec,quizQuestionNumber)}
if(typeof $(".t-records").attr("data-tilda-mode")=="undefined"){if(window.lazy=='y'){t_lazyload_update()}}
e.preventDefault()}});resultBtn.click(function(e){if(quizWrapper.hasClass('t835__quiz-published')){var showErrors=t835_setError(rec,quizQuestionNumber)}
if(showErrors){errorBoxMiddle.hide()}
if(!showErrors){quizQuestionNumber++;t835_setProgress(rec,1);t835_switchResultScreen(rec);t835_scrollToTop(quizFormWrapper);form.addClass('js-form-proccess');t835_disabledPrevBtn(rec,quizQuestionNumber)}
e.preventDefault()})}
function t835_workWithAnswerCode(rec){rec.find('.t-input-group_ri').find('input').each(function(item){var $this=$(this);if($this.val().indexOf('value::')!=-1){t835_setAnswerCode($this);var label=$this.parent().find('.t-img-select__text');label.text(label.text().split('value::')[0].trim())}});rec.find('.t-input-group_rd').find('input').each(function(item){var $this=$(this);if($this.val().indexOf('value::')!=-1){t835_setAnswerCode($this);var label=$this.parent();label.html(function(){var html=$(this).html().split('value::')[0].trim();return html})}});rec.find('.t-input-group_sb').find('option').each(function(item){var $this=$(this);if($this.val().indexOf('value::')!=-1){t835_setAnswerCode($this);$this.text($this.text().split('value::')[0].trim())}})}
function t835_setAnswerCode($this){var parameter=$this.val().split('value::')[1].trim();$this.val(parameter)}
function t835_scrollToTop(quizFormWrapper){var topCoordinateForm=quizFormWrapper.offset().top;$('html, body').animate({scrollTop:topCoordinateForm-150},0)}
function t835_checkLength(rec){var nextBtn=rec.find('.t835__btn_next');var resultBtn=rec.find('.t835__btn_result');var questionArr=t835_createQuestionArr(rec);if(questionArr.length<2){nextBtn.hide();resultBtn.show()}}
function t835_showCounter(rec,quizQuestionNumber){var counter=rec.find('.t835__quiz-description-counter');var questionArr=t835_createQuestionArr(rec);counter.html(quizQuestionNumber+1+'/'+questionArr.length)}
function t835_setError(rec,quizQuestionNumber){var questionArr=t835_createQuestionArr(rec);var currentQuestion=$(questionArr[quizQuestionNumber]);var isFieldErrorBoxExist;var arErrors=window.tildaForm.validate(currentQuestion);var showErrors;currentQuestion.addClass('js-error-control-box');if(currentQuestion.find('.t-input-error').length>0){isFieldErrorBoxExist=1}
var errorsTypeObj=arErrors[0];var arLang=window.tildaForm.arValidateErrors[window.tildaBrowserLang]||{};if(errorsTypeObj!=undefined){var errorType=errorsTypeObj.type[0];var errorTextCustom=rec.find('.t835 .t-form').find('.t-form__errorbox-middle').find('.js-rule-error-'+errorType).text();var sError='';if(errorTextCustom!=''){sError=errorTextCustom}else{sError=arLang[errorType]}
showErrors=errorType=='emptyfill'?!1:window.tildaForm.showErrors(currentQuestion,arErrors);currentQuestion.find('.t-input-error').html(sError)}
return showErrors}
function t835_hideError(rec,quizQuestionNumber){var questionArr=t835_createQuestionArr(rec);var currentQuestion=$(questionArr[quizQuestionNumber]);currentQuestion.removeClass('js-error-control-box');currentQuestion.find('.t-input-error').html('')}
function t835_setProgress(rec,index){var progressbarWidth=rec.find('.t835__progressbar').width();var progress=rec.find('.t835__progress');var questionArr=t835_createQuestionArr(rec);var progressWidth=progress.width();var progressStep=progressbarWidth/(questionArr.length);var percentProgressWidth=(progressWidth+index*progressStep)/progressbarWidth*100+'%';progress.css('width',percentProgressWidth)}
function t835_wrapCaptureForm(rec){var captureForm=rec.find('.t835__capture-form');var quizQuestion=rec.find('.t835 .t-input-group');var quizFormWrapper=rec.find('.t835__quiz-form-wrapper');quizQuestion.each(function(i){var currentQuizQuestion=$(quizQuestion[i]);var emailInputExist=$(currentQuizQuestion).hasClass('t-input-group_em');var nameInputExist=$(currentQuizQuestion).hasClass('t-input-group_nm');var phoneInputExist=$(currentQuizQuestion).hasClass('t-input-group_ph');var checkboxInputExist=$(currentQuizQuestion).hasClass('t-input-group_cb');var quizQuestionNumber=currentQuizQuestion.attr('data-question-number');var maxCountOfCaptureFields=quizFormWrapper.hasClass('t835__quiz-form-wrapper_withcheckbox')?4:3;if(quizQuestionNumber>=quizQuestion.length-maxCountOfCaptureFields){if(quizFormWrapper.hasClass('t835__quiz-form-wrapper_withcheckbox')){if(emailInputExist||nameInputExist||phoneInputExist||checkboxInputExist){currentQuizQuestion.addClass('t835__t-input-group_capture');captureForm.append(currentQuizQuestion)}}else{if(emailInputExist||nameInputExist||phoneInputExist){currentQuizQuestion.addClass('t835__t-input-group_capture');captureForm.append(currentQuizQuestion)}}}})}
function t835_createQuestionArr(rec){var quizQuestion=rec.find('.t835 .t-input-group');var questionArr=[];quizQuestion.each(function(i){var question=$(quizQuestion[i]);if(!question.hasClass('t835__t-input-group_capture')){questionArr.push(quizQuestion[i])}});return questionArr}
function t835_disabledPrevBtn(rec,quizQuestionNumber){var prevBtn=rec.find('.t835__btn_prev');quizQuestionNumber==0?prevBtn.attr('disabled',!0):prevBtn.attr('disabled',!1)}
function t835_switchQuestion(rec,quizQuestionNumber){var nextBtn=rec.find('.t835__btn_next');var resultBtn=rec.find('.t835__btn_result');var questionArr=t835_createQuestionArr(rec);$(questionArr).hide();$(questionArr[quizQuestionNumber]).show();if(quizQuestionNumber===questionArr.length-1){nextBtn.hide();resultBtn.show()}else{nextBtn.show();resultBtn.hide()}}
function t835_switchResultScreen(rec){var captureForm=rec.find('.t835__capture-form');var quizDescription=rec.find('.t835__quiz-description');var resultTitle=rec.find('.t835__result-title');var prevBtn=rec.find('.t835__btn_prev');var resultBtn=rec.find('.t835__btn_result');var submitBtnWrapper=rec.find('.t835 .t-form__submit');var questionArr=t835_createQuestionArr(rec);$(questionArr).hide();$(captureForm).show();resultBtn.hide();quizDescription.hide();resultTitle.show();submitBtnWrapper.show()}
function t835_awayFromResultScreen(rec){var captureForm=rec.find('.t835__capture-form');var quizDescription=rec.find('.t835__quiz-description');var resultTitle=rec.find('.t835__result-title');var submitBtnWrapper=rec.find('.t835 .t-form__submit');submitBtnWrapper.hide();$(captureForm).hide();quizDescription.show();resultTitle.hide()}
function t835_onSuccess(form){var inputsWrapper=form.find('.t-form__inputsbox');var inputsHeight=inputsWrapper.height();var inputsOffset=inputsWrapper.offset().top;var inputsBottom=inputsHeight+inputsOffset;var targetOffset=form.find('.t-form__successbox').offset().top;var prevBtn=form.parents('.t835').find('.t835__btn_prev');if($(window).width()>960){var target=targetOffset-200}else{var target=targetOffset-100}
if(targetOffset>$(window).scrollTop()||($(document).height()-inputsBottom)<($(window).height()-100)){inputsWrapper.addClass('t835__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:target},400);setTimeout(function(){inputsWrapper.addClass('t835__inputsbox_hidden')},400)}
var successurl=form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}
prevBtn.hide()}
function t850_init(recid){var rec=$('#rec'+recid);var container=rec.find('.t850');var doResize;t850_unifyHeights(rec);$(window).resize(function(){clearTimeout(doResize);doResize=setTimeout(function(){t850_unifyHeights(rec)},200)});$(window).load(function(){t850_unifyHeights(rec)});$('.t850').bind('displayChanged',function(){t850_unifyHeights(rec)});if(container.hasClass('t850__previewmode')){setInterval(function(){t850_unifyHeights(rec)},5000)}}
function t850_unifyHeights(rec){if($(window).width()>=960){rec.find('.t850 .t-container .t850__row').each(function(){var highestBox=0;var currow=$(this);$('.t850__inner-col',this).each(function(){var curCol=$(this);var curText=curCol.find('.t850__wrap');var curColHeight=curText.outerHeight();if(curColHeight>highestBox){highestBox=curColHeight}});$('.t850__inner-col',this).css('height',highestBox)})}else{$('.t850__inner-col').css('height','auto')}}
function t899_init(recid){t899_setMinHeight(recid);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&$isMobile){return}
t899_setMinHeight(recid)},200));$('.t899').bind('displayChanged',function(){t899_setMinHeight(recid)});if($isMobile){$(window).on('orientationchange',function(){t899_setMinHeight(recid)})}}
function t899_getWrappers(rec){var el=document.querySelector('#rec'+rec);if(!el){return}
var wrappers=el.querySelectorAll('.t899__wrapper');return wrappers}
function t899_setMinHeight(rec){var forEach=function(array,callback,scope){for(var i=0;i<array.length;i++){callback.call(scope,i,array[i])}};var wrappers=t899_getWrappers(rec);if(wrappers){forEach(wrappers,function(index,wrapper){var symbol=wrapper.querySelector('.t899__symbol');if(symbol&&symbol.offsetHeight>wrapper.offsetHeight){wrapper.style.minHeight=symbol.offsetHeight+'px'}})}}